# Generated by Django 5.0.6 on 2024-06-20 05:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_question_quiz_referral'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='uuid4',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
