# Generated by Django 5.0.6 on 2024-06-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile_uuid4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='uuid4',
            new_name='uuid',
        ),
    ]
