# Generated by Django 5.0.6 on 2024-06-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_uuid4_profile_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name': 'Реферальная система', 'verbose_name_plural': 'Реферальная система'},
        ),
        migrations.RenameField(
            model_name='userquiz',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
