# Generated by Django 5.0.6 on 2024-06-20 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_referral_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('user_quiz', 'question')},
        ),
    ]
