# Generated by Django 5.0.6 on 2024-06-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_useranswer_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_required',
            field=models.BooleanField(default=False),
        ),
    ]
