# Generated by Django 5.0.6 on 2024-07-01 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_question_is_recommendation_question_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Точность'),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Продолжительность'),
        ),
    ]
