# Generated by Django 5.0.6 on 2024-07-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_userquiz_accuracy_userquiz_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='height',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='weight',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
