# Generated by Django 5.0.6 on 2024-07-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_userquiz_height_alter_userquiz_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquiz',
            name='height',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userquiz',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
