# Generated by Django 5.0.6 on 2024-07-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_question_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_editable',
            field=models.BooleanField(default=False, verbose_name='Изменяемый'),
        ),
    ]
