# Generated by Django 5.0.6 on 2024-07-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_payment_subscriptionpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionpayment',
            old_name='yokassa_id',
            new_name='yookassa_id',
        ),
    ]
