# Generated by Django 5.0.6 on 2024-08-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0022_alter_subscriptionpayment_subscription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="duration",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
